# Generated by Django 6.0.1 on 2026-02-23 13:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_customerfield_customertag_customer_anniversary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackForm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('form_type', models.CharField(choices=[('rating_5', '1-5 Rating'), ('nps_10', 'NPS (0-10)'), ('stars_5', '5 Stars'), ('thumbs', 'Thumbs Up/Down'), ('text_only', 'Text Only')], default='stars_5', max_length=20, verbose_name='Form Type')),
                ('trigger_type', models.CharField(choices=[('manual', 'Manual'), ('post_sale', 'After Sale'), ('post_appointment', 'After Appointment'), ('post_ticket', 'After Support Ticket')], default='manual', max_length=20, verbose_name='Trigger')),
                ('trigger_delay_hours', models.IntegerField(default=24, help_text='Hours to wait after the event before sending the feedback request', verbose_name='Trigger Delay (hours)')),
                ('include_comment', models.BooleanField(default=True, verbose_name='Include Comment Field')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('thank_you_message', models.TextField(blank=True, default='', help_text='Message shown after the customer submits feedback', verbose_name='Thank You Message')),
            ],
            options={
                'db_table': 'feedback_feedbackform',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeedbackSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('auto_send_post_sale', models.BooleanField(default=False, help_text='Automatically send feedback request after a completed sale', verbose_name='Auto-send after sale')),
                ('auto_send_post_appointment', models.BooleanField(default=False, help_text='Automatically send feedback request after a completed appointment', verbose_name='Auto-send after appointment')),
                ('minimum_days_between_requests', models.IntegerField(default=30, help_text='Minimum number of days to wait before sending another feedback request to the same customer', verbose_name='Minimum days between requests')),
                ('default_form', models.ForeignKey(blank=True, help_text='Default feedback form to use when auto-sending', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='feedback.feedbackform', verbose_name='Default Form')),
            ],
            options={
                'verbose_name': 'Feedback Settings',
                'verbose_name_plural': 'Feedback Settings',
                'db_table': 'feedback_feedbacksettings',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeedbackResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('score', models.IntegerField(blank=True, help_text='Numeric score (0-10 for NPS, 1-5 for ratings, 0/1 for thumbs)', null=True, verbose_name='Score')),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('actioned', 'Actioned')], db_index=True, default='new', max_length=20, verbose_name='Status')),
                ('reviewed_by', models.UUIDField(blank=True, null=True, verbose_name='Reviewed By')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Reviewed At')),
                ('staff_notes', models.TextField(blank=True, verbose_name='Staff Notes')),
                ('related_sale', models.UUIDField(blank=True, null=True, verbose_name='Related Sale')),
                ('related_appointment', models.UUIDField(blank=True, null=True, verbose_name='Related Appointment')),
                ('related_ticket', models.UUIDField(blank=True, null=True, verbose_name='Related Ticket')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_responses', to='customers.customer', verbose_name='Customer')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='feedback.feedbackform', verbose_name='Form')),
            ],
            options={
                'db_table': 'feedback_feedbackresponse',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['hub_id', 'status'], name='feedback_fe_hub_id_2760f6_idx'), models.Index(fields=['hub_id', 'form'], name='feedback_fe_hub_id_f8f512_idx'), models.Index(fields=['hub_id', 'customer'], name='feedback_fe_hub_id_29c7d6_idx'), models.Index(fields=['hub_id', 'created_at'], name='feedback_fe_hub_id_246523_idx')],
            },
        ),
    ]
